
USE `DOCUMENT_MANAGEMENT`;
Create table Training (`Training_ID` INT NOT NULL auto_increment,`TRAINING_NAME` VARCHAR(40) NOT NULL,primary key(`Training_ID`));
ALTER TABLE Training AUTO_INCREMENT=1;
INSERT INTO Training(`TRAINING_NAME`) Values('PROCESS MANAGEMENT'),('DEVICE MANAGEMENT'),('SECURITY MANAGEMENT'),('FILE MANAGEMENT');